### ISSUE TITLE
Problemas con el servidor

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2143-2020-1/proyecto#100]
Hola!

Por alguna razón que no entiendo no puedo entrar al servidor de rails y ver el archivo de nuestro proyecto. En concola al hacer rails server me sale esto:

> => Booting Puma
=> Rails 5.2.4.2 application starting in development
=> Run `rails server -h` for more startup options
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...

> * Version 3.12.4 (ruby 2.6.6-p146), codename: Llamas in Pajamas
> * Min threads: 5, max threads: 5
> * Environment: development
> * Listening on tcp://localhost:3000
> Use Ctrl-C to stop
> Started GET "/" for ::1 at 2020-04-22 15:30:59 -0400
> 

> PG::ConnectionBad (could not connect to server: Connection refused (0x0000274D/10061)
>         Is the server running on host "localhost" (::1) and accepting
>         TCP/IP connections on port 5432?
> could not connect to server: Connection refused (0x0000274D/10061)
>         Is the server running on host "localhost" (127.0.0.1) and accepting
>         TCP/IP connections on port 5432?

Alguna idea de qué podría ser? Antes si funcionaba. Creo que falló después de agregar devise, pero la gema sí está en mi rails, entonces no entiendo :(

Gracias!

**Comment by daleal** [comment]
Hola! Parece ser que tu conexión a la base de datos falla. Revisa si efectivamente `PostgreSQL` está corriendo en tu máquina, y si está escuchando en el puerto `5432`.

**Comment by ChayoPerez** [comment]
Cómo me aseguro de que esas dos condiciones se cumplen?
Gracias!

**Comment by daleal** [comment]
Depende. Tienes Windows, Linux o macOS? Si estás usando `pgadmin`, ¿puedes conectarte a la base de datos a través de esa herramienta? Si no, ¿puedes conectarte a través de la línea de comandos usando el comando `psql`?

**Comment by ChayoPerez** [comment]
Estoy usando Windows. La línea de comandos no responde a psql :( He instalado postgres como tres veces ya y no entiendo qué es lo que sale mal T_T

**Comment by valerojasm** [comment]
Hola! Por lo que tengo entendido, efectivamente en Windows la instalación de postgres no incluye el comando como variable de entorno, por lo que no puedes correrlo a menos de que lo agregues manualmente. Revisa [esto](https://stackoverflow.com/questions/36629963/how-can-i-start-postgresql-on-windows) a ver si te sirve, si no, te recomiendo usar Windows Subsystem for Linux (wsl), en Windows 10 me parece que es tan fácil como bajar Ubuntu desde el store. (Edit: Hay más literatura para consolas unix como lo son las de macOS y Linux, por eso mi recomendación, quizás te sea más fácil 😸 )

**Comment by ChayoPerez** [comment]
Instalé postgresql de nuevo y el error cambió!

```
'Puma starting in single mode...
* Version 3.12.4 (ruby 2.6.6-p146), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
Exiting
Traceback (most recent call last):
        25: from bin/rails:4:in `<main>'
        24: from bin/rails:4:in `require'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<top (required)>'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `perform'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `tap'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:53:in `start'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:327:in `start'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/rack/handler/puma.rb:73:in `run'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/launcher.rb:186:in `run'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/single.rb:98:in `run'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/runner.rb:153:in `load_and_bind'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:90:in `parse'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:90:in `each'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:106:in `block in parse'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:266:in `add_tcp_listener'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:266:in `each'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:267:in `block in add_tcp_listener'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:273:in `add_tcp_listener'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:273:in `new'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-3.12.4/lib/puma/binder.rb:273:in `initialize': Permission denied - bind(2) for "::1" port 3000 (Errno::EACCES)`
```

**Comment by daleal** [comment]
> Llamas in Pajamas

Lo que te acaba de pasar probablemente se debe a que la instancia anterior de `rails` no terminó correctamente y el puerto `3000` se ve "ocupado" por un proceso, por lo que no puedes volver a usarlo. Para remediar esta situación puedes reiniciar tu computador.

**Comment by ChayoPerez** [comment]
Reinicié el computador y no pasó nada :( Antes por lo menos me mandaba (en localhost:3000) a una página en rojo que decía que no había conexión, pero desde que cambié postgres me sale el error de arriba en consola y en localhost:3000 no me sale nada (osea el server no podría estar más lejos de estar conectado xd)
Localhost:5432 tampoco me lleva a nada

**Comment by daleal** [comment]
Creo que lo mejor que podrías hacer sería lo que te recomendó @valerojasm

**Comment by ChayoPerez** [comment]
Me bajé Ubuntu para Windows y cambió nuevamente el error que sale. 

```
> andie@Artemisa:~/prueba/grupo52-proyecto$ rails server
=> Booting Puma
=> Rails 5.2.4.2 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...

> * Version 3.12.4 (ruby 2.6.5-p114), codename: Llamas in Pajamas

> * Min threads: 5, max threads: 5

> * Environment: development

> Exiting

> Traceback (most recent call last):

        32: from bin/rails:4:in `<main>'
        31: from /home/andie/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        30: from /home/andie/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        29: from /home/andie/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
        28: from /home/andie/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        27: from /home/andie/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        26: from /home/andie/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        25: from /home/andie/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        24: from /home/andie/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        23: from /home/andie/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<main>'
        22: from /home/andie/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
        21: from /home/andie/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
        20: from /home/andie/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        19: from /home/andie/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        18: from /home/andie/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        17: from /home/andie/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `perform'
        16: from /home/andie/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `tap'
        15: from /home/andie/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        14: from /home/andie/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:53:in `start'
        13: from /home/andie/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/server.rb:327:in `start'
        12: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/rack/handler/puma.rb:73:in `run'
        11: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/launcher.rb:186:in `run'
        10: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/single.rb:98:in `run'
         9: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/runner.rb:153:in `load_and_bind'
         8: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `parse'
         7: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:90:in `each'
         6: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:106:in `block in parse'
         5: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `add_tcp_listener'
         4: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:266:in `each'
         3: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:267:in `block in add_tcp_listener'
         2: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `add_tcp_listener'
         1: from /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `new'

> /home/andie/.rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/binder.rb:273:in `initialize': Permission denied - bind(2) for "127.0.0.1" port 3000 (Errno::EACCES)<
```

Busqué en google, pero no me ha ayudado hasta ahora

**Comment by ChayoPerez** [comment]
Puede estarme perjudicando el hecho de que hice esto y no una partición?

También quería agregar que el problema al ingresar a la página es este:

> FATAL: Peer authentication failed for user "postgres"

He intentado cambiar el usuario y la contraseña pero no me deja

**Comment by daleal** [comment]
El error es realmente el mismo (no puedes hacer _bind_ al puerto). Una partición siempre es lo mejor que puedes hacer porque los entornos de Linux generalmente están más documentados, pero el _tradeoff_ de tener que hacer la partición puede ser muy grande.
Con respecto a tu segundo problema, en #88 alguien tuvo un problema similar.
Por favor, si uno de tus problemas se resuelve y aparece otro, agradecería que hicieras una issue distinta.
