### ISSUE TITLE
Error con rails generate devise user

### ISSUE THREAD

**Issue by sluchsinger** [IIC2143-2020-1/proyecto#99]
Hola estoy intentando usar la gema devise pero cuando ejecuto el comando "rails generate devise user" no funciona y me muestra lo siguiente:

```
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/evented_file_update_checker.rb:132:in `start_with?': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/evented_file_update_checker.rb:132:in `block (2 levels) in directories_to_watch'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/evented_file_update_checker.rb:132:in `any?'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/evented_file_update_checker.rb:132:in `block in directories_to_watch'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/evented_file_update_checker.rb:131:in `reject'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/evented_file_update_checker.rb:131:in `directories_to_watch'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/evented_file_update_checker.rb:55:in `initialize'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/i18n_railtie.rb:61:in `new'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/i18n_railtie.rb:61:in `initialize_i18n'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/i18n_railtie.rb:19:in `block in <class:Railtie>'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:347:in `each'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:347:in `call'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        from C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
        from C:/Users/Sebastián/Apprails/config/environment.rb:5:in `<top (required)>'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/command/actions.rb:28:in `require_environment!'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
Y no se cual es el error que se produce
Gracias

**Comment by daleal** [comment]
Hola! 2 preguntas:

1. Te ha pasado con otra app de rails en tu computador? O solo ahora que quieres probar devise?
2. Puedes pegar el contenido de `config/environment.rb` como _formatted text_ por favor?

**Comment by sluchsinger** [comment]
1. Lo probé en otra app y pasaba lo mismo, solo me pasa con este comando
2. 
```
# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!
```

**Comment by daleal** [comment]
Podrías correr este comando y decirme qué pasa?

```
rails generate controller CreditCards index new create
```

**Comment by daleal** [comment]
Apostaría [_50 bucks_](https://youtu.be/PAp-HFOAf6w?t=139) a que es porque tu nombre de usuario tiene un tilde (`Sebastián`)

**Comment by sluchsinger** [comment]
Si me pasa lo mismo, antes no me pasaba puede ser porque acabo de cambiar mi version de ruby de 2.6.5 a 2.6.3? Y si es lo del tilde, en esta carpeta en especifico no me aparece la opcion cambiar nombre

**Comment by daleal** [comment]
Veo muy poco probable que sea la versión de ruby (aunque podrías tratar cambiándola), pero parece ser un problema de rails cuando intenta crear un archivo. No puedes cambiarle el nombre a la carpeta de tu usuario porque las referencias directas a esa carpeta se perderían y se rompería todo tu usuario en el sistema operativo. Lo que tendrías que intentar hacer sería crear un usuario nuevo en tu computador sin símbolos ni caracteres especiales en el nombre (yo lo nombraría `sebastian`, por ejemplo) e intentar en ese usuario.

**Comment by sluchsinger** [comment]
Movi la app a una carpeta que se llama Rails y ahora me aparece esto:
```
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require': Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile (LoadError)
```

**Comment by sluchsinger** [comment]
Por que ahora me pide una nueva gema que nunca había visto?

**Comment by daleal** [comment]
No lo sé, pero corre `bundle install` y se debería resolver.

**Comment by sluchsinger** [comment]
Si ya lo había corrido

**Comment by sluchsinger** [comment]
Le agrego esa gema?

**Comment by sluchsinger** [comment]
Ya lo solucioné tuve que sacar la línea
```
config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```
que estaba en config\enviroments\development.rb
aunque no se en que le afecta, tenia entendido que se necesitaba

**Comment by daleal** [comment]
Me suena a que con eso perderás las capacidades de _hot reload_ en development. Sigo creyendo que es por el tilde en el nombre de usuario

**Comment by sluchsinger** [comment]
Y que son esas capacidades? Afectan al desarrolo de una aplicación? Movi la app a la carpeta Sebastián y si me funcionó el rails generate controller, así que pareciera que el problema era esa línea

**Comment by daleal** [comment]
Cuando hagas un cambio en un archivo, me parece que vas a tener que detener el servidor de `rails` y volver a iniciarlo para poder ver los cambios en la página (en vez de solamente recargarla)
